CREATE PROCEDURE [dbo].[Product_Add]	
	    @id                      BIGINT = NULL,
        @name                    NVARCHAR(30), 
		@manufacturer            NVARCHAR(30),  
		@price                   MONEY,
		@width                   DECIMAL = NULL, 
		@height                  DECIMAL = NULL,
		@length                  DECIMAL = NULL, 
		@weight                  DECIMAL = NULL,
		@prodYear                SMALLINT,
		@warranty                SMALLINT = NULL,
		@volume      			 DECIMAL = NULL,
		@power             		 DECIMAL = NULL,
		@maxTemperature          DECIMAL = NULL,
		@batteryCapacity         DECIMAL = NULL,
		@memorySize              DECIMAL = NULL,
		@screenDiagonal          DECIMAL = NULL,
		@screenResolutionWidth   SMALLINT = NULL,
		@screenResolutionHeight  SMALLINT = NULL,
		@numberOfModes           TINYINT = NULL,
		@hdmi            		 BIT = NULL,
		@jack             		 BIT = NULL,
		@miniJack       		 BIT = NULL,
		@lte       				 BIT = NULL,
		@tabletMode              BIT = NULL,
		@diskDrivePresence       BIT = NULL,
		@smartHomeFunction       BIT = NULL,    
		@steamGeneratorFunction  BIT = NULL,
		@wetCleaningFunction     BIT = NULL,		
		@quickDefrostFunction    BIT = NULL,
		@cameraFunction          BIT = NULL,
		@tvFunction              BIT = NULL,
		@grillFunction           BIT = NULL
	as
	begin
        INSERT INTO [dbo].[Product]
			(
    [Name],
    Manufacturer,
	Price,
	Width,
	Height,
	[Length],
	[Weight],
	ProdYear,
	Warranty,
	Volume,
	[Power],
	MaxTemperature,
	BatteryCapacity,
	MemorySize,
	ScreenDiagonal,
	ScreenResolutionWidth,
	ScreenResolutionHeight,
	NumberOfModes,
	HDMI,
	Jack,
	MiniJack,
	LTE,
	TabletMode,
	DiskDrivePresence,
	SmartHomeFunction,
	SteamGeneratorFunction,
	WetCleaningFunction,
	QuickDefrostFunction,
	CameraFunction,
	TvFunction,
	GrillFunction
	)
		VALUES
			(
		@name, 
		@manufacturer,
		@price,
		@width,
		@height,
		@length,
		@weight,
		@prodYear,
		@warranty,
		@volume,
		@power,
		@maxTemperature,
		@batteryCapacity,
		@memorySize,
		@screenDiagonal,
		@screenResolutionWidth,
		@screenResolutionHeight,
		@numberOfModes,
		@hdmi,
		@jack,
		@miniJack,
		@lte,
		@tabletMode,
		@diskDrivePresence,
		@smartHomeFunction,    
		@steamGeneratorFunction,
		@wetCleaningFunction,		
		@quickDefrostFunction,
		@cameraFunction,
		@tvFunction,
		@grillFunction
		);
        SET @id = CAST(SCOPE_IDENTITY() AS [INT])
		EXEC Product_GetById @id		
    end;