create table [dbo].[Product]  (
    Id bigint IDENTITY (1, 1) PRIMARY KEY,
    [Name] nvarchar(30) NOT NULL,
    Manufacturer nvarchar(30) NOT NULL,
	Price money NOT NULL,
	Width decimal NOT NULL,
	Height decimal NOT NULL,
	[Length] decimal NOT NULL,
	[Weight] decimal NOT NULL,
	ProdYear smallint NOT NULL,
	Warranty smallint,
	Volume decimal,
	[Power] decimal,
	MaxTemperature decimal,
	BatteryCapacity decimal,
	MemorySize decimal,
	ScreenDiagonal decimal,
	ScreenResolutionWidth smallint,
	ScreenResolutionHeight smallint,
	NumberOfModes tinyint,
	HDMI bit,
	Jack bit,
	MiniJack bit,
	LTE bit,
	TabletMode bit,
	DiskDrivePresence bit,
	SmartHomeFunction bit,
	SteamGeneratorFunction bit,
	WetCleaningFunction bit,
	QuickDefrostFunction bit,
	CameraFunction bit,
	TvFunction bit,
	GrillFunction bit
);